language: go

go:
- 1.17.x 

addons:
  packages: &common_packages
  - libx11-dev
  - libxcursor-dev
  - libgl1-mesa-dev

script:
- go test ./... -v
- go build -o gorpn gui/fyne/main.go
- go build -o gorpn-cli cli/main.go
