name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Configure
      run: sudo apt-get install -y libgl1-mesa-dev libwayland-bin xorg-dev libx11-dev libxcursor-dev

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race -covermode=atomic -cover -coverprofile=coverage.out -v ./...
      
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
